apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vm-event-operator-system

resources:
- namespace/namespace.yaml
- database/postgres.yaml
- deploy/rbac.yaml
- deploy/configmap.yaml
- deploy/deployment.yaml
- deploy/service.yaml
- deploy/tls-proxy-config.yaml
- console/plugin.yaml
- samples/retention-cronjob.yaml

# Container images
images:
- name: vm-event-processor
  newName: quay.io/andy_krohg/openshift-vm-event-processor
- name: vm-events-plugin
  newName: quay.io/andy_krohg/openshift-vm-event-console-plugin
