apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vm-activity-plugin

resources:
- namespace/namespace.yaml
- database/postgres.yaml
- deploy/rbac.yaml
- deploy/configmap.yaml
- deploy/deployment.yaml
- deploy/service.yaml
- deploy/tls-proxy-config.yaml
- console/plugin.yaml
- samples/retention-cronjob.yaml
- webhook/mutating-webhook.yaml
