# Containerfile for local builds - expects dist/ to be pre-built
FROM registry.access.redhat.com/ubi9/nginx-124:latest
COPY dist /usr/share/nginx/html
USER 1001
ENTRYPOINT ["nginx", "-g", "daemon off;"]
