apiVersion: v1
kind: Service
metadata:
  name: vm-events-api
  namespace: vm-event-operator-system
  labels:
    app: vm-event-processor
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: vm-events-api-cert
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: vm-event-processor
